// pages/_app.tsx
import type { AppProps } from "next/app";
import { Lato } from "next/font/google";
import "@/app/globals.css";

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MyApp({ Component, pageProps }: AppProps) {
  return (
    <main className={`${lato.className} antialiased`}>
      <Component {...pageProps} />
    </main>
  );
}
